### PR TITLE
Changed how ItemNamesConfig and ItemWatchConfig parses files. Fixes #1.

### LINKED ISSUE #1: Exception error on Linux
I downloaded the latest release of durian and attempted to run it. I was instantly given an exception error, and the program then did nothing else.
I also tried version 0.1, which had the same result.

Reproduction and error:

```
dryvnt:durian/ $ java-jar durian-v0.1.1.jar
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
    at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$152(LauncherImpl.java:182)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
    at net.thirdy.durian.util.config.ItemWatchConfig$ItemWatch.fromConfig(ItemWatchConfig.java:92)
    at net.thirdy.durian.util.config.ItemWatchConfig.lambda$3(ItemWatchConfig.java:37)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
    at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    at net.thirdy.durian.util.config.ItemWatchConfig.loadItemWatchList(ItemWatchConfig.java:38)
    at net.thirdy.durian.ui.DurianApplication.start(DurianApplication.java:102)
    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$159(LauncherImpl.java:863)
    at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$172(PlatformImpl.java:326)
    at com.sun.javafx.application.PlatformImpl.lambda$null$170(PlatformImpl.java:295)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$171(PlatformImpl.java:294)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139)
    ... 1 more
```

### PR DESCRIPTION
**Pull request by Dryvnt**
The regular expressions probably aren't perfect, but they should fix this specific bug I was having, as well as avoid others like it that might have showed up.

### CODE REVIEW

**Comment by thirdy** [comment]
Can you describe this specific bug?

Note the following documentation in itemwatch.txt

```
; This is a comment
; Each line represent 1 item watch
; There are 4 required information, the League, Full Item Name, Currency and Amount, separated by a pipe '|'
; These token will be trimmed, e.g. "   chaos   " will be read as "chaos"

Standard|Tabula Rasa|chaos|5
```

**Comment by Dryvnt** [comment]
I described the bug in the issue I put here. Issue #1, even! :p

Basically an empty itemwatch file somehow passes the filter, which then leads to an out of bounds exception when this line gets split and indexed into. 

As for what this fix does: I changed the filters for ItemWatch and ItemName to use regular expressions instead. I haven't found a bug with ItemName, but being consistent can't hurt, and it protects against a malformed file. 

These regular expressions only matches lines that don't begin with ';', that then have some text followed by a '|' followed by some text etc., until the appropriate amount of pipes have been found. 

This should also safeguard against malformed itemwatch lists, where people forgot pipes or some such.

**Comment by thirdy** [comment]
I pushed a unit test, I'm suspecting there's a problem with how I used the split method.
Can your run ItemWatchConfigTest on your machine?

As for the regex, I think the pipe should be escape as in "^;.+\|.+"
I'll look into this more.

Thanks btw.

**Comment by thirdy** [comment]
i merged in your changes, but no I'm getting IndexOutOfBounds. So I made a bit of adjustment to your regex.

Let me know that doesn't work for you.

**Comment by Dryvnt** [comment]
Seems to work fine for me, I'd consider this issue fixed and closed.

**Pull request merged**
