### PR TITLE
Added Some stuff

### PR DESCRIPTION
**Pull request by Dominik-O22**
Added cirt chance for spells,
Added 2.1uniques
Broadened Currency RegExp

### CODE REVIEW

**Comment by thirdy** [comment]
nice work. will merge it, though I think the regex on chaos orb might conflict with the buyout regex, might be, haven't checked

**Comment by Dominik-O22** [comment]
yeah, totally didn't realize that they were two different things, didn't even realize that there was a buyout file, considering that the fuse will also, after looking through the buyout files i bit i noticed that  you aleady have a conflict with exalt

```
(([0-9]+)?(\.)?([0-9]{1,2})?)(ex|exalted)   //from buyout
Exalt|Ex|Exalted(Orb)?                      //from currencies
```

both match for ex, but the moment you add a number in front of it it breaks the conflict the same would happen with the conflicts i generated, causing:

```
glove ex   //causes no result, but senseless query
glove 1ex //causes result and is a senseful query
```

**Comment by Dominik-O22** [comment]
just another off topic thing, i just found that in the buyout there are options like this 

```
ge(([0-9]+)?(\.)?([0-9]{1,2})?)(ch|chaos)
```

why is there a ge infornt of the buyout? is there a point to it and why does the ge format only support max buyout and not min-maxbuyout format

**Comment by thirdy** [comment]
ge means "greater than or equal to".

this was a request to do some search, i've forgotten, we'll have to closely look at it more

**Pull request merged**
